constants_pt = {
    waitInstructions: "Aguarde instruções do professor!<br><br>Esta aplicação não ainda não foi ativada! 😄",
    wait: "Aguarde...",
    apiError: "Ops... Houve algum erro na API.😓<br><br>Já estou resolvendo! Em breve tudo voltará ao normal.🤓",
    apiErrorTitle: "🔴 Ops... Erro na API!",
    dayShiftTitle: "1. Turno ⌚️",
    shiftQuestion: "Em qual turno você estuda?",
    diurnal: "☀️ Diurno",
    nightShift: "🌒 Noturno",
    dlcTitle: "🖥️ EaD",
    disciplineSelectTitle: "2. Selecione a disciplina 🎓",
    select: "Selecione...",
    ops: "🟡 Ops...",
    shouldSelectDiscipline: "É preciso selecionar uma disciplina!",
  };

  constants_en = {
    waitInstructions: "Hold on! Wait for the professor instructions!<br><br>This application is not active yet! 😄",
    wait: "Wait...",
    apiError: "Ops... There was an error in the API.😓<br><br>I'm already solving it! Soon everything will return to normal.🤓",
    apiErrorTitle: "🔴 Ops... API error!",
    dayShiftTitle: "1. Shift ⌚️",
    shiftQuestion: "What shift do you study?",
    diurnal: "☀️ Morning",
    nightShift: "🌒 Night",
    dlcTitle: "🖥️ Online",
    disciplineSelectTitle: "2. Select the discipline",
    select: "Select...",
    ops: "🟡 Ops...",
    shouldSelectDiscipline: "You need to select a discipline!",
  };